# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven CI and Lint Formatting

on: 
  push:
    tags-ignore:
      - automated

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-java@v1
      with:
        java-version: "11"
    
    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v3.1.0
      with:
        args: "--set-exit-if-changed --replace"
    
    - name: Build with Maven
      run: mvn -B package --file portfolio/pom.xml
